config/routes.rb
Openbook::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  resources :customers
  resources :invoicelines
  resources :invoices
  resources :pricesheets
  resources :posts
  resources :images
  resources :ratesheets
  resources :periods
  resources :roomrates
  resources :roomtypes
  resources :contacts
  resources :zones
  resources :provinces
  resources :countries
  resources :hotels
  resources :partners
  resources :currencies
  resources :organizations

  get "dashboard/index"
  namespace :account do
    resources :invoicelines
    resources :invoices do
      get :sendconfirm, on: :member
      get :confirmpayment, on: :member
    end
    resources :customers
  end
  namespace :admin do
    root to: "dashboard#index"
    resources :clients
    resources :organizations
    resources :currencies
    resources :partners
    resources :hotels do
      resources :images
      resources :ratesheets
      get :create_ratesheet, on: :member
      post :create_ratesheet, on: :member
      put  :create_ratesheet, on: :member, to: "hotels#update_ratesheet"
      delete  :destroy_ratesheet, on: :member
      get :all_ratesheet, on: :member
      get :edit_ratesheet, on: :member
      get :hotelinfo, on: :member
      get :viewratesheet, on: :member
      resources :pricesheets
    end
    resources :countries
    resources :provinces
    resources :zones
    resources :contacts
    resources :roomtypes
    resources :roomrates
    resources :periods
    resources :ratesheets
    resources :images
    resources :pricesheets
  end
  resources :clients

  get "home/index"
  root to: "home#underconstruct"

  match "confirmpayment/:invoice_no" =>  "account/invoices#confirmpayment"
  match "admin/hotels/new" => "admin/hotels#new"

end

app/models/currency.rb
class Currency
  include Mongoid::Document
  has_many :organizations
  has_many :partners
  has_many :invoices
  has_many :ratesheets
  has_and_belongs_to_many :hotels
  field :name, type: String
  field :description, type: String
  field :code, type: String
  field :rate, type: BigDecimal
  field :icon, type: String
  def fullname
    "#{name}(#{code} -rate #{rate}/@us)"
  end
end

app/controllers/admin/currencies_controller.rb
class Admin::CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to [:admin,@currency], notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to [:admin,@currency], notice: 'Currency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to admin_currencies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  # GET /currencies
  # GET /currencies.json
  def index
    @currencies = Currency.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @currencies }
    end
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
    @currency = Currency.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/new
  # GET /currencies/new.json
  def new
    @currency = Currency.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @currency }
    end
  end

  # GET /currencies/1/edit
  def edit
    @currency = Currency.find(params[:id])
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(params[:currency])

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render json: @currency, status: :created, location: @currency }
      else
        format.html { render action: "new" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /currencies/1
  # PUT /currencies/1.json
  def update
    @currency = Currency.find(params[:id])

    respond_to do |format|
      if @currency.update_attributes(params[:currency])
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency = Currency.find(params[:id])
    @currency.destroy

    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/currencies_helper.rb
module Admin::CurrenciesHelper
end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/views/currencies/_form.html.erb
<%= form_for(@currency) do |f| %>
  <% if @currency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@currency.errors.count, "error") %> prohibited this currency from being saved:</h2>

      <ul>
      <% @currency.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :rate %><br />
    <%= f.text_field :rate %>
  </div>
  <div class="field">
    <%= f.label :icon %><br />
    <%= f.text_field :icon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/index.html.erb
<h1>Listing currencies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Code</th>
    <th>Rate</th>
    <th>Icon</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @currencies.each do |currency| %>
  <tr>
    <td><%= currency.name %></td>
    <td><%= currency.description %></td>
    <td><%= currency.code %></td>
    <td><%= currency.rate %></td>
    <td><%= currency.icon %></td>
    <td><%= link_to 'Show', currency %></td>
    <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
    <td><%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Currency', new_currency_path %>

app/views/currencies/new.html.erb
<h1>New currency</h1>

<%= render 'form' %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @currency.name %>
</p>

<p>
  <b>Description:</b>
  <%= @currency.description %>
</p>

<p>
  <b>Code:</b>
  <%= @currency.code %>
</p>

<p>
  <b>Rate:</b>
  <%= @currency.rate %>
</p>

<p>
  <b>Icon:</b>
  <%= @currency.icon %>
</p>


<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Back', currencies_path %>