config/routes.rb
Openbook::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users
  resources :customers
  resources :invoicelines
  resources :invoices
  resources :pricesheets
  resources :posts
  resources :images
  resources :ratesheets
  resources :periods
  resources :roomrates
  resources :roomtypes
  resources :contacts
  resources :zones
  resources :provinces
  resources :countries
  resources :hotels
  resources :partners
  resources :currencies
  resources :organizations

  get "dashboard/index"
  namespace :account do
    resources :invoicelines
    resources :invoices do
      get :sendconfirm, on: :member
      get :confirmpayment, on: :member
    end
    resources :customers
  end
  namespace :admin do
    root to: "dashboard#index"
    resources :clients
    resources :organizations
    resources :currencies
    resources :partners
    resources :hotels do
      resources :images
      resources :ratesheets
      get :create_ratesheet, on: :member
      post :create_ratesheet, on: :member
      put  :create_ratesheet, on: :member, to: "hotels#update_ratesheet"
      delete  :destroy_ratesheet, on: :member
      get :all_ratesheet, on: :member
      get :edit_ratesheet, on: :member
      get :hotelinfo, on: :member
      get :viewratesheet, on: :member
      resources :pricesheets
    end
    resources :countries
    resources :provinces
    resources :zones
    resources :contacts
    resources :roomtypes
    resources :roomrates
    resources :periods
    resources :ratesheets
    resources :images
    resources :pricesheets
  end
  resources :clients

  get "home/index"
  root to: "home#underconstruct"

  match "confirmpayment/:invoice_no" =>  "account/invoices#confirmpayment"
  match "admin/hotels/new" => "admin/hotels#new"

end

app/models/hotel.rb
class Hotel
  include Mongoid::Document
  include Mongoid::Timestamps

  field :latitude, type: Float
  field :longitude, type: Float
  field :zoom, type: Integer
  field :gmaps,     :type => Boolean

  belongs_to :country
  belongs_to :province
  belongs_to :zone
  has_many :contacts , dependent: :destroy , autosave: true
  has_many :periods, dependent: :destroy , autosave: true
  has_many :ratesheets , dependent: :destroy , autosave: true
  has_and_belongs_to_many :roomtypes
  has_and_belongs_to_many :roomrates
  has_and_belongs_to_many :currencies
  accepts_nested_attributes_for :contacts
  accepts_nested_attributes_for :ratesheets, reject_if:  lambda { |a| a[:date].blank? }, allow_destroy:  true
  accepts_nested_attributes_for :periods, allow_destroy: true
  validates_uniqueness_of :name1
  validates_uniqueness_of :name2
  field :_id, type: String, default: -> {name1}
  field :name1, type: String
  field :name2, type: String
  field :address1, type: String
  field :address2, type: String
  field :street, type: String
  field :postal, type: String
  field :telephone, type: String
  field :fax, type: String
  field :email, type: String
  field :url, type: String
  field :reservationemail, type: String
  field :localtion, type: Array
  field :star, type: Integer
  field :isactive, type: Boolean
  field :info, type: String
  embeds_many :hotel_images, as: :imageable, class_name: "Image", cascade_callbacks: true
  accepts_nested_attributes_for :hotel_images
  mount_uploader :logo,  LogoUploader

  def show_tiny_logo(logo)
    logo.file? ? image_tag(logo.url(:tiny_thumb)) : "no image"
  end

  def latlng
    [self.latitude,self.longitude]
  end
end

app/controllers/admin/hotels_controller.rb
class Admin::HotelsController < ApplicationController
  include ActionView::Helpers::AssetTagHelper
  # GET /hotels
  # GET /hotels.json
  def index
    @hotel = Hotel.new
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
    @lat   = @hotel.latitude
    @lng   = @hotel.longitude
    @ratesheet = @hotel.ratesheets.build
    respond_to do |format|
      format.html
      format.json { render json: @hotel }
    end

  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to [:admin,@hotel], notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])
    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to [:admin,@hotel], notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to admin_hotels_url }
      format.json { head :no_content }
    end
  end
  def all_ratesheet
    @hotel = Hotel.find(params[:id])
    @ratesheets = @hotel.ratesheets
    respond_to do |format|
      format.js
    end
  end
  def edit_ratesheet
    @ratesheet = Ratesheet.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def hotelinfo
    @hotel = Hotel.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def destroy_ratesheet

    @ratesheet = Ratesheet.find(params[:id])
    @ratesheet.destroy
    @hotel = @ratesheet.hotel

    respond_to do |format|
      format.html { redirect_to edit_admin_hotel_url(@hotel), alert: "Ratesheet Deleted"}
      format.json { head :no_content }
    end
  end
  def update_ratesheet
    @ratesheet = Ratesheet.find(params[:id])
    respond_to do |format|
      if @ratesheet.update_attributes(params[:ratesheet])
        format.js  {alert("update  #{@ratesheet}success"); }
      end
    end
  end

  def create_ratesheet
    @ratesheet = Ratesheet.find_or_create_by(params[:ratesheet])

    respond_to do |format|
      if @ratesheet.save
        @vf = @ratesheet.period.valid_from
        @vt = @ratesheet.period.valid_to

        @vf.upto(@vt) do |d|
          @pricesheet = @ratesheet.pricesheets.build
          @pricesheet.date = d
          @pricesheet.day = d.strftime('%A')
          @pricesheet.minstay = 1
          @pricesheet.price = 0.0
          @pricesheet.message = "message"
          @pricesheet.isactive = true
          @pricesheet.save
        end
        @pricesheets = @ratesheet.pricesheets
        format.js
      else
      end
    end
  end


  def viewratesheet
   @ratesheet = Ratesheet.find(params[:id])
   respond_to do |format|
     format.js
   end
  end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hotels }
    end
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/new
  # GET /hotels/new.json
  def new
    @hotel = Hotel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hotel }
    end
  end

  # GET /hotels/1/edit
  def edit
    @hotel = Hotel.find(params[:id])
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(params[:hotel])

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render json: @hotel, status: :created, location: @hotel }
      else
        format.html { render action: "new" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hotels/1
  # PUT /hotels/1.json
  def update
    @hotel = Hotel.find(params[:id])

    respond_to do |format|
      if @hotel.update_attributes(params[:hotel])
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel = Hotel.find(params[:id])
    @hotel.destroy

    respond_to do |format|
      format.html { redirect_to hotels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/hotels_helper.rb
module Admin::HotelsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/admin/hotels/_hotelform.html.erb
<%= form_for([:admin,@hotel], html: {multipart: true, class: "form-horizontal"}) do |f| %>

  <% if @hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
        <% @hotel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <legend class="bluegray">Logo</legend>
    <div class="control-group">
      <%=  show_tiny_logo(@hotel.logo) %>
      <div class="controls">
        <%= f.file_field :logo %>
      </div>
    </div>
  </fieldset>

  <div class="control-group">
    <%= f.label :country , class: "control-label"%>
    <div class="controls">
      <%= f.collection_select :country_id, Country.all.to_a, :id, :name, include_blank: true %>
    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :province , class: "control-label"%>
        <div class="controls">
          <%= f.grouped_collection_select :province_id, Country.all.to_a, :provinces, :name, :id, :name, include_blank: true %>
        </div>
      </div>

    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :zone , class: "control-label"%>
        <div class="controls">
          <%= f.grouped_collection_select :zone_id, Province.all.to_a, :zones, :name, :id, :name, include_blank: true %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :name1 , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :name1 %>
        </div>
      </div>

    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :name2 , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :name2 %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :address1 , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :address1 %>
        </div>
      </div>

    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :address2 , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :address2 %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :street , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :street %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :postal , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :postal %>
        </div>
      </div>

    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :telephone , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :telephone %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :fax , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :fax %>
        </div>
      </div>

    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :email , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :email %>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :url , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :url %>
        </div>
      </div>

    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :reservationemail , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :reservationemail , class: "control-label"%>
        </div>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <%= f.label :localtion , class: "control-label"%>
        <div class="controls">
          <%= f.text_field :localtion %>
        </div>
      </div>

    </div>
    <div class="span4">
      <div class="control-group">
        <%= f.label :star , class: "control-label"%>
        <div class="controls">
          <%= f.number_field :star %>
          <ul class="rating">
            <% (1..5).each do |i| %>
              <li id="rate_<%= i %>" data-stars="<%=i %>" class="rating_star"></li>
            <% end %>
          </ul>
        </div>
      </div>

    </div>
  </div>
  <div class="control-group">
    <%= f.label :isactive , class: "control-label"%>
    <div class="controls">
      <%= f.check_box :isactive %>
    </div>
  </div>
  <fieldset>
    <legend class="bluegray">Room Type</legend>
    <div class="control-group">
      <div class="controls">
        <%= hidden_field_tag "hotel[roomtype_ids][]",nil %>
        <% Roomtype.all.to_a.each do |roomtype|  %>

          <%= check_box_tag "hotel[roomtype_ids][]", roomtype.id, @hotel.roomtype_ids.include?(roomtype.id) %>
          <%= roomtype.name %>
        <% end %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend class="bluegray">Room Rate</legend>
    <div class="control-group">
      <div class="controls">
        <%= hidden_field_tag "hotel[roomrate_ids][]",nil %>
        <% Roomrate.all.to_a.each do |roomrate|  %>

          <%= check_box_tag "hotel[roomrate_ids][]", roomrate.id, @hotel.roomrate_ids.include?(roomrate.id) %>
          <%= roomrate.name %>
        <% end %>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend class="bluegray">Currency</legend>
    <div class="control-group">
      <div class="controls">
        <%= hidden_field_tag "hotel[currency_ids][]",nil %>
        <% Currency.all.to_a.each do |currency|  %>

          <%= check_box_tag "hotel[currency_ids][]", currency.id, @hotel.currency_ids.include?(currency.id) %>
          <%= currency.fullname %>
        <% end %>
      </div>
    </div>
  </fieldset>


    <legend class="bluegray"> Period
    </legend>
  <fieldset>
    <%= f.fields_for :periods do |period| %>
      <%= render  'period_fields', f: period %>
    <% end %>
    <%= link_to_add_fields "+add", f, :periods %>
  </fieldset>
  <fieldset>

    <legend class="bluegray">Infomation
    </legend>
    <%= f.cktext_area :info  %>
  </fieldset>
  <fieldset>
    <legend class="bluegray">Gallery  <%= link_to "+add", new_admin_hotel_image_path(@hotel) unless @hotel.id.nil? %> </legend>
    <ul class="thumbnails">
      <% @hotel.hotel_images.each do |image| %>
        <li class="span2">
          <a class="thumbnail" href="#lightbox" data-toggle="lightbox">
            <%=image_tag image.image.url(:tiny_thumb) %>
          </a>
          <div id="lightbox" class="lightbox hide fade" tabindex="-1" role="dialog" aria-hidden="true">
            <div class='lightbox-content'>
              <%=image_tag image.image.url %>
              <div class="lightbox-caption"><p>Your caption here</p></div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>

  </fieldset>

  <fieldset>
    <legend class="bluegray">Map
      <p> Latitude: <%= f.text_field  :latitude %>
          Longitude: <%= f.text_field  :longitude %>
          Zoom: <%= f.text_field :zoom %>
      </p>
    </legend>

    <div style="position:relative">
      <div id="map_canvas" style="float: left; width: 100%; height: 400px;"></div>
      <!-- <div id="pano" style="float: left; width: 50%; height: 400px;"></div> -->
      <div style="clear: both;"></div>
    </div>
  </fieldset>

  <div class="control-group">
    <div class="form-actions">
      <%= f.submit 'manage hotel', class: 'btn btn-primary btn-large' %>
    </div>
  </div>
<% end %>

app/views/admin/hotels/_hotels.html.erb
  <tr>
    <td><%=  show_tiny_logo(hotel.logo) %></td>
    <td><%= hotel.name1 %></td>
    <td><%= hotel.address1 %></td>
    <td><%= hotel.street %></td>
    <td><%= hotel.province.name %></td>
    <td><%= hotel.country.name %></td>
    <td><%= hotel.star %></td>
    <td><%= hotel.isactive %></td>
    <td>
      <%= link_to "<i class=\"icon-zoom-in\"></i>".html_safe, [:admin,hotel],class: 'btn btn-small pull-right', data: {toggle: "tooltip", placement: "top"}, title: "show" %>
      <%= link_to "<i class=\"icon-pencil\"></i>".html_safe, edit_admin_hotel_path(hotel),class: 'btn btn-small pull-right' , data: {toggle: "tooltip", placement: "top"}, title: "edit"%>
   <%= link_to "<i class=\"icon-trash\"></i>".html_safe, [:admin,hotel],class: 'btn btn-small pull-right', method: :delete, data: { confirm: 'Are you sure?' } , data: {toggle: "tooltip", placement: "top"}, title: "delete"%></td>
  </tr>

app/views/admin/hotels/_listratesheet.html.erb
<% unless ratesheet.name.nil? %>
 <tr>
    <td > <%= ratesheet.name %> </td>
    <td > <%= ratesheet.hotel.name1 %> </td>

    <td  > <%= ratesheet.roomtype.name %> </td>

    <td > <%= ratesheet.roomrate.name %> </td>
    <td > <%= ratesheet.period.name %>  </td>
    <td >
      <%= link_to "<i class=\"icon-trash\"></i>".html_safe,destroy_ratesheet_admin_hotel_path(ratesheet),class: 'pull-right', method: :delete, data: { confirm: 'Are you sure?' } %>&nbsp;

      <%= link_to  "<i class=\"icon-pencil\"></i>".html_safe,edit_ratesheet_admin_hotel_path(ratesheet),class: 'pull-right',  :remote => true, 'data-toggle' => 'tab', 'data-target' => '#ratesheet' %> &nbsp;
    </td>
</tr>
<% end %>

app/views/admin/hotels/_period_fields.html.erb
<fieldset>
  <table>
    <tr>
      <td><%= f.label :name, "period name" %></td>
      <td><%= f.text_field :name %></td>
      <td><%= f.label :valid_from, "Valid From" %></td>
      <td><%= f.text_field :valid_from %></td>
      <td><%= f.label :valid_to, "Valid To" %></td>
      <td><%= f.text_field :valid_to %></td>
      <td><%= f.hidden_field :_destroy %>
      <%= link_to "remove", '#', class: "remove_fields" %></td>
    </tr>
  </table>
</fieldset>

app/views/admin/hotels/_pricesheet.html.erb
<% @pricesheet = pricesheet %>
<tr>
  <td style="width: 10%">  </td>
  <td style="width: 30%"> <%= pricesheet.date.strftime('%b %d, %Y')  %> </td>
  <td style="width: 20%"> <%= pricesheet.day  %> </td>
  <td style="width: 10%"><%= best_in_place @pricesheet, :minstay  %> </td>
  <td style="width: 10%"> <%= best_in_place @pricesheet, :price  %> </td>
  <td style="width: 20%"> <%= best_in_place @pricesheet, :message  %> </td>
  <td style="width: 10%"> <%= best_in_place @pricesheet, :isactive  %> </td>
</tr>

app/views/admin/hotels/_ratesheet.html.erb
<% @hotel = @ratesheet.hotel %>
<%= form_for @ratesheet, url: create_ratesheet_admin_hotel_path , html: {id: 'ratesheet', class: 'form-horizontal', remote: true} do |f|  %>
  <%= hidden_field_tag  "ratesheet[hotel_id]", @hotel.id %>
  <div class="row">
    <div class="span8">
      <div class="control-group">
        <p class="control-label">Name</p>
        <div class="controls">
          <%= f.text_field  :name, class:  "fullwidth" %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="span4">
      <div class="control-group">
        <p class="control-label">Roomtype</p>
        <div class="controls">
          <%= select_tag  "ratesheet[roomtype_id]",
            options_from_collection_for_select(@hotel.roomtypes,:id,:name,@ratesheet.roomtype_id), prompt: "Please Select Roomtype" %>
        </div>
      </div>
    </div>
    <div class="span4">
      <div class="control-group">
        <p class="control-label">Roomrate </p>
        <div class="controls">
          <%= select_tag "ratesheet[roomrate_id]", options_from_collection_for_select(@hotel.roomrates,:id,:name,@ratesheet.roomrate_id), prompt: "Please Select Roomrate" %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="span8">
      <div class="control-group">
        <p class="control-label">period</p>
        <div class="controls">
          <%= select_tag  "ratesheet[period_id]", options_from_collection_for_select(@hotel.periods,:id,:fullname,@ratesheet.period_id), class: "fullwidth", prompt: "Select period" %>
        </div>
      </div>

    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit 'add ratesheet', class: 'btn' %>
    </div>
  </div>

<% end %>

<div class="pricesheetholder">
</div>

app/views/admin/hotels/all_ratesheet.js.erb
$("#profile").html("<%= escape_javascript(render(@ratesheets)) %>");

app/views/admin/hotels/edit.html.erb
<h1 class="babyblue">Editing hotel</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@hotel] %> |
<%= link_to 'Back', admin_hotels_path %>

app/views/admin/hotels/edit_ratesheet.js.erb
$('#ratesheetholder').html("<%= escape_javascript(render 'admin/hotels/ratesheet', object:  @ratesheet, as: :ratesheet) %>");
$('#pricesheetholder').html("<%= escape_javascript(render partial: 'admin/hotels/pricesheet', collection: @ratesheet.pricesheets, as: :pricesheet) %>")

app/views/admin/hotels/hotelinfo.js.erb
$('#profile').html("<%= escape_javascript(render  'hotelform2', hotel: @hotel) %>")

app/views/admin/hotels/index.html.erb
<div class="header">
  <h3 style="color: #FFF;"> Listing hotels </h3>
</div>
<div class="subheader">
  <a href="#newHotelModal" class="btn pull-right" data-toggle="modal"><i class="icon-plus-sign"></i>Add Hotel</a>
</div>

<div class="mainbody">
 <table class="t1  table-striped ">
  <tr>
    <th>Logo</th>
    <th>Name1</th>
    <th>Address1</th>
    <th>Street</th>
    <th>Province</th>
    <th>Country</th>
    <th>Star</th>
    <th>Isactive</th>
    <th></th>
  </tr>

<%= render :partial => 'hotels', collection: @hotels, as: :hotel %>
</table>

<br />

<div id="newHotelModal" class="modal hide fade" >
    <button type="button" class="close" data-dismiss="modal">×</button></h1>
    <div class="page-header">
        <h3>Quick Add New Hotel </h3>
    </div>

    <%= render :partial => 'shortform' %>
</div>
<div class="footer">
</div>

app/views/admin/hotels/new.html.erb
<h1>New hotel
  <%= link_to "<i class=\"icon-arrow-left\"></i>Back".html_safe, admin_hotels_path, class: "btn pull-right" %>
</h1>


<%= render 'form' %>

app/views/admin/hotels/show.html.erb
<p id="notice"><%= notice %></p>
<table class="table table-striped table-bordered table-condensed">
<tr>
  <td class="first">Name1:</td>
  <td><%= @hotel.name1 %> </td>
</tr>

<tr>
  <td>Name2:</td>
  <td><%= @hotel.name2 %> </td>
</tr>

<tr>
  <td>Address1:</td>
  <td> <%= @hotel.address1 %> </td>
</tr>

<tr>
  <td>Address2:</td>
  <td> <%= @hotel.address2 %> </td>
</tr>

<tr>
  <td>Address3:</td>
  <td> <%= @hotel.address3 %> </td>
</tr>

<tr>
  <td>City:</td>
  <td> <%= @hotel.city %> </td>
</tr>

<tr>
  <td>Postal:</td>
  <td> <%= @hotel.postal %> </td>
</tr>

<tr>
  <td>Telephone:</td>
  <td> <%= @hotel.telephone %> </td>
</tr>

<tr>
  <td>Fax:</td>
  <td> <%= @hotel.fax %> </td>
</tr>

<tr>
  <td>Email:</td>
  <td> <%= @hotel.email %> </td>
</tr>

<tr>
  <td>Url:</td>
  <td><%= @hotel.url %> </td>
</tr>

<tr>
  <td>Reservationemail:</td>
  <td> <%= @hotel.reservationemail %>  </td>
</tr>

<tr>
  <td>Localtion:</td>
  <td> <%= @hotel.localtion %> </td>
</tr>

<tr>
  <td>Star:</td>
  <td> <%= @hotel.star %> </td>
</tr>

<tr>
  <td>Isactive:</td>
  <td> <%= @hotel.isactive %> </td>
</tr>

</table>
<%= link_to 'Edit', edit_admin_hotel_path(@hotel) %> |
<%= link_to 'Back', admin_hotels_path %>

app/views/admin/hotels/viewratesheet.js.erb
$('#viewsheetholder').html("<%= escape_javascript(render partial: 'admin/hotels/viewratesheet', object: @ratesheet, as: :ratesheet ) %>");